### ISSUE TITLE
Struktur på kurset

### ISSUE THREAD

**Issue by enerammer** [KUBDatalab/R-EDA_old#3]
Lave en struktur for kurset.

**Comment by enerammer** [comment]
Noteform
Lesson 1 - Before we start - næsten som det er til R-beginning R - dog uden fx instalation af pakker (er allerede udkommenteret)

Lesson 2 - Downloade filer og indlæse filer (med readr), installation og library på pakker, gemme filer i objekter/variable, dataframe, operationer på dataframe

Lesson 3 - datamanipulation - have nogle ting vi vil undersøge - bruge select, filter, group_by, rename, arrange, summarise mv. - klare de problemer vi møder, fx NA, dato som er strenge, tal som er strenge (andet?) - joine dataframes, pipe

Lesson 4 - visualisering i ggplot

**Comment by enerammer** [comment]
Er lidt i tvivl om om lesson 3 og 4 kan deles op i to eller om vi simpelthen bare skal lave lesson 3 og frem som cases vi gerne vil undersøge - så vi når fra select til ggplot i hver lesson

**Comment by chrbknudsen** [comment]
> d

Jeg tror vi med fordel deler det i to på siden. Jeg tror det gør det en smule mere anvendeligt som reference for de studerende efter kurset.

**Comment by chrbknudsen** [comment]
Lesson 2+3 let udbygget. Eller: "operationer på dataframe er ret dækket af nr. 3, er de ikke?"
Sådan downloader vi filen.
Så kigger vi på den - hvad er der egentlig i de forskellige kolonner.
Så indlæser vi den. Og det gør vi med en funktion fra en pakke som vi installerer. => install.packages vs library
Det første ark (så vi skal lige sikre at vi faktisk har det ønskede ark som det første)
Det giver en god snak om argumenter til funktioner.
Pipen - filter på et enkelt flyselskab.
Select så vi kun ser på interessante kolonnner.
Summarise til gennemsnitlig forsinkelse - eller noget.
Group_by så vi kan få dem alle.
Arrange, så vi kan finde den mest forsinkede
Mutate  - der skal vi lige finde noget meningsfuldt at mutate på.
